# Read about DVC pipeline configuration (https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#stages)
# to customize your stages even more
stages:
  feature_building:
    cmd: python src/noshow/features/feature_pipeline.py
    deps:
    - data/raw/NL.txt
    - data/raw/poliafspraken_no_show.csv
    - src/noshow/features/feature_pipeline.py
    outs:
    - data/processed/featuretable.parquet
  train:
    cmd: python src/noshow/model/train_model.py
    deps:
    - src/noshow/model/train_model.py
    - data/processed/featuretable.parquet
    outs:
    - output/models/no_show_model_cv.pickle
params:
- output/dvclive/params.yaml
metrics:
- output/dvclive/metrics.json
plots:
- output/dvclive/plots/metrics:
    x: step
- output/dvclive/plots/sklearn/roc.json:
    template: simple
    x: fpr
    y: tpr
    title: Receiver operating characteristic (ROC)
    x_label: False Positive Rate
    y_label: True Positive Rate
- output/dvclive/plots/sklearn/calibration.json:
    template: simple
    x: prob_pred
    y: prob_true
    title: Calibration Curve
    x_label: Mean Predicted Probability
    y_label: Fraction of Positives
- output/dvclive/plots/sklearn/precision_recall.json:
    template: simple
    x: recall
    y: precision
    title: Precision-Recall Curve
    x_label: Recall
    y_label: Precision
