"""Add actual clinic name

Revision ID: 0cd216c41f64
Revises: 6d815bb77dc1
Create Date: 2025-12-24 12:48:23.036739

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cd216c41f64"
down_revision: Union[str, None] = "6d815bb77dc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apiprediction",
        sa.Column("clinic_actual_name", sa.String(length=64), nullable=True),
        schema="noshow",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apiprediction", "clinic_actual_name", schema="noshow")
    # ### end Alembic commands ###
