"""Remove last_call_date column from ApiPatient

Revision ID: 15a94b3d2592
Revises: 84310a5c9e71
Create Date: 2025-03-18 15:58:29.630764

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15a94b3d2592"
down_revision: Union[str, None] = "84310a5c9e71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apipatient", "last_call_date", schema="noshow")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apipatient",
        sa.Column("last_call_date", sa.DATE(), autoincrement=False, nullable=True),
        schema="noshow",
    )
    # ### end Alembic commands ###
