"""add timestamp

Revision ID: 20f444146781
Revises:
Create Date: 2024-10-30 09:56:46.886479

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20f444146781"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apicallresponse",
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        schema="noshow",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apicallresponse", "timestamp", schema="noshow")
    # ### end Alembic commands ###
