[clinic_phonenumbers]
"RF&S Ergotherapie" = "58831"
"RF&S Fysiotherapie" = "58831" 
"RF&S Logopedie" = "58831"
"RF&S Maatschappelijk werk" = "58831"
"RF&S Psychologie" = "58831"
"RF&S Revalidatiegeneeskunde" = "58831" 
"RF&S Sportgeneeskunde" = "58831"
"Longziekten" = "56192"
"Centrum voor Thuisbeademing" = "58865"
"Kind-KNO" = "54902"
"Kind-Neurologie" = "67370"
"Kind-Orthopedie" = "67470"
"Kind-Plastische chirurgie" = "53594"
"Kind-Nefrologie" = "54075"
"Kind-Endocrinologie" = "54075"
"Kind-Dermatologie" = "54075"
"Kind-Algemene Pediatrie" = "54075"

[feature_building]
mute_period = 6
appointments_last_days = 14
minutes_early_cutoff = 60
