name: Linting

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  build:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: uv sync --only-dev

    - name: Analysing the code with ruff
      run: |
        uv run ruff check .
