name: Push main to public repo on release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the tag from the release
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || 'v0.0.2' }}
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --unset-all http.https://github.com/.extraheader

      - name: Push the tag to the public repo
        env:
          TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
            git remote add public https://${TOKEN}@github.com/UMCU-Digital-Health/No_Show.git
            git push public ${{ github.event.release.tag_name || 'v0.0.2' }}:refs/tags/${{ github.event.release.tag_name || 'v0.0.2' }} --force
            git push public ${{ github.event.release.tag_name || 'v0.0.2' }}:refs/heads/main --force